/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.prueba1;

/**
 *
 * @author linhaopeng
 */
public class ItemAutor extends javax.swing.JPanel {
    
    /**
     * Creates new form AutorItem
     * @param Autor
     */
    public ItemAutor(String Autor) {
        initComponents();
        NombreAutor.setText(Autor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AutorLabel = new javax.swing.JLabel();
        NombreAutor = new javax.swing.JLabel();
        ButtonVerObras = new javax.swing.JButton();

        AutorLabel.setText("Autor :");

        NombreAutor.setText("jLabel2");

        ButtonVerObras.setText("Ver Sus Obras");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(AutorLabel)
                .addGap(18, 18, 18)
                .addComponent(NombreAutor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 391, Short.MAX_VALUE)
                .addComponent(ButtonVerObras)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AutorLabel)
                    .addComponent(NombreAutor)
                    .addComponent(ButtonVerObras))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AutorLabel;
    private javax.swing.JButton ButtonVerObras;
    private javax.swing.JLabel NombreAutor;
    // End of variables declaration//GEN-END:variables
}
