/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interficie.vistas.Items;

import Interficie.vistas.FramePrincipal;
import Interficie.vistas.VentanaSecundaria.VentInfoDoc;

/**
 *
 * @author linhaopeng
 */
public class ItemDocumento extends javax.swing.JPanel {
    private FramePrincipal framePrincipal;
    /**
     * Creates new form DocumentManage
     * @param framePrincipal
     * @param autor
     * @param titulo
     */
    public ItemDocumento(FramePrincipal framePrincipal,String autor,String titulo) {
        this.framePrincipal = framePrincipal;
        initComponents();
        NombreAutor.setText(autor);
        Titulo.setText(titulo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AutorLabel = new javax.swing.JLabel();
        TituloLabel = new javax.swing.JLabel();
        ButtonEliminar = new javax.swing.JButton();
        NombreAutor = new javax.swing.JLabel();
        Titulo = new javax.swing.JLabel();
        ButtonVer = new javax.swing.JButton();

        AutorLabel.setLabelFor(NombreAutor);
        AutorLabel.setText("Autor:");

        TituloLabel.setLabelFor(Titulo);
        TituloLabel.setText("Titulo:");

        ButtonEliminar.setText("Borrar");
        ButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEliminarActionPerformed(evt);
            }
        });

        NombreAutor.setText("jLabel3");

        Titulo.setText("jLabel4");

        ButtonVer.setText("Ver");
        ButtonVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonVerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(AutorLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NombreAutor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TituloLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 204, Short.MAX_VALUE)
                .addComponent(ButtonVer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonEliminar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AutorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NombreAutor)
                    .addComponent(Titulo)
                    .addComponent(TituloLabel)
                    .addComponent(ButtonEliminar)
                    .addComponent(ButtonVer))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonVerActionPerformed
        // TODO add your handling code here:
        String autor = NombreAutor.getText();
        String titulo = Titulo.getText();
        VentInfoDoc infoDoc = new VentInfoDoc(this.framePrincipal,autor,titulo);
        infoDoc.setVisible(true);
        //Center the frame
        infoDoc.setLocationRelativeTo(null);
    }//GEN-LAST:event_ButtonVerActionPerformed

    private void ButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEliminarActionPerformed
        // TODO: falta hacer ventana de seguro:
        
        String autor = NombreAutor.getText();
        String titulo = Titulo.getText();
        this.framePrincipal.removeDocument(autor,titulo);
    }//GEN-LAST:event_ButtonEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AutorLabel;
    private javax.swing.JButton ButtonEliminar;
    private javax.swing.JButton ButtonVer;
    private javax.swing.JLabel NombreAutor;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel TituloLabel;
    // End of variables declaration//GEN-END:variables
}
